language: cpp

compiler: clang

env:
  - GOAL=build

before_install:
  - ./install-toolchain.sh

install:
  - export TOOLCHAINPATH=$PWD/gcc-arm-none-eabi-8-2018-q4-major/bin
  - export PATH=$TOOLCHAINPATH:$PATH

script:
  - make -j $(nproc) SPEEDYBEEF7V3
